# Generated by Django 3.2.7 on 2021-09-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('travelapp', '0002_place_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='place1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('img1', models.ImageField(upload_to='picture')),
                ('caption', models.TextField()),
                ('desc1', models.TextField()),
            ],
        ),
    ]
